### Create argocd Project for POC-B
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: in-cluster
  namespace: argocd
spec:
  description: Master Cluster (in-cluster)
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

### Create POC-B seed app in argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  # DIFF
  name: bootstrap-master
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  ### Config
  # DIFF
  project: in-cluster
  source:
    repoURL: https://github.com/aliusmiles/k8s-argocd.git
    targetRevision: HEAD
    path: bootstrap
