---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  syncPolicy:
    automated:
      prune: true
    validate: true

  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}

  project: default

  source:
    path: argocd-bootstrap
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
