---
apiVersion: v1
kind: Namespace
metadata:
  name: cerebro


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cerebro
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  syncPolicy:
    automated:
      prune: true
    validate: true

  destination:
    namespace: cerebro
    server: {{ .Values.spec.destination.server }}

  project: default
  source:
    path: applications/cerebro
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values-{{ .Values.spec.destination.clusterName }}.yaml

