{{- if has "cert-manager" .Values.applications -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  syncPolicy:
    automated:
      prune: true
    validate: true

  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}

  project: default

  source:
    path: applications/cert-manager
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /status
      kind: CustomResourceDefinition
{{- end -}}
