apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  syncPolicy:
    automated:
      prune: true
    validate: true

  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}

  project: default

  source:
    path: applications/metrics-server
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

