apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    targetRevision: 1.29.0
