---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
  namespace: cert-manager
  # annotations:
  # create issuer after cert-manager deployed
  # argocd.argoproj.io/hook: PostSync
spec:
  selfSigned: {}
